version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'  # Port for Nginx Proxy Manager UI
      - '443:443'
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"  # Using SQLite for Nginx Proxy Manager
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - web

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - web

  db:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: npmjExaSJcGqiZTuYFaUAWqzrFprQFEVHnl
      POSTGRES_DB: railway
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - web

networks:
  web:
    driver: bridge

volumes:
  postgres_data:
